export const schoolStages = [
  {
    stage: '小学',
    grades: [
      {
        year: 1,
        yearName:'一年级',
        courses: {
          语文: true,
          数学: true,
          英语: true,
          科学: true,
          音乐: true,
          体育: true,
          美术: true,
          道德与法治:true
        },
      },
      {
        year: 2,
        yearName:'二年级',
        courses: {
          语文: true,
          数学: true,
          英语: true,
          科学: true,
          音乐: true,
          体育: true,
          美术: true,
          道德与法治:true
        },
      },
      {
        year: 3,
        yearName:'三年级',
        courses: {
          语文: true,
          数学: true,
          英语: true,
          科学: true,
          音乐: true,
          体育: true,
          美术: true,
          道德与法治:true
        },
      },
      {
        year: 4,
        yearName:'四年级',
        courses: {
          语文: true,
          数学: true,
          英语: true,
          科学: true,
          音乐: true,
          体育: true,
          美术: true,
          道德与法治:true
        },
      },
      {
        year: 5,
        yearName:'五年级',
        courses: {
          语文: true,
          数学: true,
          英语: true,
          科学: true,
          音乐: true,
          体育: true,
          美术: true,
          道德与法治:true
        },
      },
      {
        year: 6,
        yearName:'六年级',
        courses: {
          语文: true,
          数学: true,
          英语: true,
          科学: true,
          音乐: true,
          体育: true,
          美术: true,
          道德与法治:true
        },
      },
    ],
  },
  {
    stage: '初中',
    grades: [
      {
        year: 7,
        yearName:'初一',
        courses: {
          语文: true,
          数学: true,
          英语: true,
          物理: true,
          化学: true,
          生物: true,
          地理: true,
          历史: true,
          政治: true,
          音乐: true,
          体育: true,
          美术: true,
        },
      },
      {
        year: 8,
        yearName:'初二',
        courses: {
          语文: true,
          数学: true,
          英语: true,
          物理: true,
          化学: true,
          生物: true,
          地理: true,
          历史: true,
          政治: true,
          音乐: true,
          体育: true,
          美术: true,
        },
      },
      {
        year: 9,
        yearName:'初三',
        courses: {
          语文: true,
          数学: true,
          英语: true,
          物理: true,
          化学: true,
          生物: true,
          地理: true,
          历史: true,
          政治: true,
          音乐: true,
          体育: true,
          美术: true,
        },
      },
    ],
  },
  {
    stage: '高中',
    grades: [
      {
        year: 10,
        yearName:'高一',
        courses: {
          语文: true,
          数学: true,
          英语: true,
          物理: true,
          化学: true,
          生物: true,
          地理: true,
          历史: true,
          政治: true,
        },
      },
      {
        year: 11,
        yearName:'高二',
        courses: {
          语文: true,
          数学: true,
          英语: true,
          物理: true,
          化学: true,
          生物: true,
          地理: true,
          历史: true,
          政治: true,
        },
      },
      {
        year: 12,
        yearName:'高三',
        courses: {
          语文: true,
          数学: true,
          英语: true,
          物理: true,
          化学: true,
          生物: true,
          地理: true,
          历史: true,
          政治: true,
  
        },
      },
    ],
  },
];
